In [5]:
import numpy as np
arr = np.arange(-5,11)
arr
smf.ols

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(-5,11,2)
arr

array([-5, -3, -1,  1,  3,  5,  7,  9])

In [12]:
arr1 = arr.reshape(4,2)
arr1

array([[-5, -3],
       [-1,  1],
       [ 3,  5],
       [ 7,  9]])

In [13]:
# slicing a[i:j:k]
arr[0:3:2]

array([-5, -1])

In [15]:
arr1[1:4:2]

array([[-1,  1],
       [ 7,  9]])

In [16]:
arr2 = np.array([[0,2,4,6], [1, 3, 5, 7], [9, 10, 11, 12]])
arr2

array([[ 0,  2,  4,  6],
       [ 1,  3,  5,  7],
       [ 9, 10, 11, 12]])

In [19]:
for elem in np.nditer(arr2):
    print(elem)

0
2
4
6
1
3
5
7
9
10
11
12


In [21]:
# use slicing to extract parts of arr2
arr3 = arr2[1:3, 1:4] # rows 1 and 2, columns 1, 2, and 3
arr3

array([[ 3,  5,  7],
       [10, 11, 12]])

In [22]:
print(arr2)

[[ 0  2  4  6]
 [ 1  3  5  7]
 [ 9 10 11 12]]


In [28]:
overall_mean = np.mean(arr2)
x_mean = np.mean(arr2, axis = 0)

y_mean = np.mean(arr2, axis = 1)

overall_mean, x_mean, y_mean

(5.833333333333333,
 array([3.33333333, 5.        , 6.66666667, 8.33333333]),
 array([ 3. ,  4. , 10.5]))

In [29]:
np.std([1, 2, 3, 4, 5, 6])

1.707825127659933

In [30]:
np.var([1, 2, 3, 4, 5, 6])

2.9166666666666665

In [31]:
weight = [10,10,0,0]

In [33]:
np.average([1,2,3,4], weights = weight)

1.5